name = "libsingular_julia_jll"
uuid = "ae4fbd8f-ecdb-54f8-bbce-35570499b30e"
version = "0.47.8+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
Singular_jll = "43d676ae-4934-50ba-8046-7a96366d613b"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "~1.10, ~1.11, ~1.12, ~1.13, ~1.14"
libcxxwrap_julia_jll = "~0.14.5"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
